page:
  size: letter
  orientation: portrait
  margins:
    top: 0.3
    bottom: 0.3
    left: 0.3
    right: 0.3

fonts:
  family: Helvetica
  title_size: 14
  goal_line_size: 10
  quarter_label_size: 10
  month_label_size: 9
  week_number_size: 8

colors:
  grid_line: [0, 0, 0]        # Black
  light_grid: [180, 180, 180]  # Light grey
  text: [0, 0, 0]              # Black
  week_number: [120, 120, 120]  # Mid grey for week numbers
  row_stripe: [230, 230, 230]  # Darker grey for alternating blocks

layout:
  quarterly_column_width: 1.75
  monthly_column_width: 1.75
  weekly_column_width: 3.5
  checkbox_size: 0.15
  row_height: 0.185
  weekly_line_weight: 0.3
  show_vertical_separators: false
  show_row_stripes: true
  row_stripe_interval: 4
  label_padding_y: 0.07

output:
  directory: output
  filename: goal_tracker_template.pdf
